export interface WorkspaceIcon {
    name: string; // Lucide icon component name
    label: string; // Display label for icon picker
}

export const WORKSPACE_ICONS: WorkspaceIcon[] = [
    { name: "Home", label: "General/Home" },
    { name: "Briefcase", label: "Work" },
    { name: "Code", label: "Coding/Dev" },
    { name: "FolderKanban", label: "Project" },
    { name: "Heart", label: "Personal" },
    { name: "Stethoscope", label: "Medical/Health" },
    { name: "GraduationCap", label: "Education/Learning" },
    { name: "ShoppingCart", label: "Shopping" },
    { name: "DollarSign", label: "Finance" },
    { name: "Car", label: "Automotive" },
    { name: "Gamepad2", label: "Gaming" },
    { name: "Tv", label: "Watch/TV" },
    { name: "Film", label: "Movies/Series" },
    { name: "Youtube", label: "YouTube" },
    { name: "Music", label: "Music" },
    { name: "Palette", label: "Design/Creative" },
    { name: "Camera", label: "Photography" },
    { name: "Plane", label: "Travel" },
    { name: "UtensilsCrossed", label: "Food/Recipes" },
    { name: "Dumbbell", label: "Fitness" },
    { name: "BookOpen", label: "Reading/Books" },
    { name: "Newspaper", label: "News" },
    { name: "MessageSquare", label: "Social/Chat" },
    { name: "Mail", label: "Email" },
    { name: "Calendar", label: "Calendar/Events" },
    { name: "Users", label: "Team/Collaboration" },
    { name: "Rocket", label: "Startup/Launch" },
    { name: "Bug", label: "Bug Tracking" },
    { name: "Search", label: "Research" },
    { name: "Sparkles", label: "AI/Experiments" },
    { name: "Laptop", label: "Development" },
    { name: "Monitor", label: "Screens/Display" },
    { name: "Globe", label: "Web/International" },
    { name: "Building", label: "Office/Business" },
    { name: "Database", label: "Database/Storage" },
    { name: "Server", label: "Backend/Infrastructure" },
    { name: "Cloud", label: "Cloud Services" },
    { name: "Lock", label: "Security/Private" },
    { name: "Shield", label: "Protection" },
    { name: "Zap", label: "Performance/Speed" },
    { name: "Target", label: "Goals/Objectives" },
    { name: "TrendingUp", label: "Analytics/Growth" },
    { name: "Bell", label: "Notifications/Alerts" },
    { name: "Star", label: "Favorites/Important" },
    { name: "Bookmark", label: "Saved/Reference" },
    { name: "Archive", label: "Archives/Old Projects" },
    { name: "Package", label: "Packages/Products" },
    { name: "Gift", label: "Gifts/Presents" },
    { name: "Coffee", label: "Breaks/Casual" },
    { name: "Pizza", label: "Food Delivery" },
    { name: "Headphones", label: "Audio/Podcasts" },
    { name: "Mic", label: "Recording/Voice" },
    { name: "Video", label: "Video Content" },
    { name: "Image", label: "Images/Graphics" },
    { name: "FileText", label: "Documents/Notes" },
    { name: "Pen", label: "Writing/Editing" },
    { name: "Compass", label: "Navigation/Exploration" },
    { name: "Map", label: "Maps/Locations" },
    { name: "Clock", label: "Time Management" },
    { name: "Timer", label: "Productivity/Timers" },
];
