import { ThemePreset } from "./types";

export const THEME_PRESETS: ThemePreset[] = [
    {
        name: "Blue Gradient",
        configuration: {
            themeType: "dark",
            theme: "blue",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,

            backgroundImageOpacity: 0.45,
            backgroundImageSaturation: 0.75,
            backgroundImageBlur: 17,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageSize: 745,
            backgroundImagePositionX: 78,
            backgroundImagePositionY: 49,
            backgroundImageUrl: "https://images.pexels.com/photos/3418396/pexels-photo-3418396.jpeg?auto=compress&cs=tinysrgb&h=1500",

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/3418396/pexels-photo-3418396.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Blue Frost",
        configuration: {
            themeType: "dark",
            theme: "blue",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageUrl: "https://images.pexels.com/photos/1292998/pexels-photo-1292998.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImageOpacity: 0.4,
            backgroundImageSaturation: 0.6,
            backgroundImageBlur: 10,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/1292998/pexels-photo-1292998.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Digital",
        configuration: {
            themeType: "dark",
            theme: "green",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundForTabFavicon: false,
            backgroundImageBlur: 7,
            backgroundImageEnabled: true,
            backgroundImageHue: 270,
            backgroundImageOpacity: 0.45,
            backgroundImageSaturation: 0.75,
            backgroundImageUrl: "https://images.pexels.com/photos/33158875/pexels-photo-33158875.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImageContrast: 1,
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/33158875/pexels-photo-33158875.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 270,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Blue Lights 1",
        configuration: {
            themeType: "dark",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageOpacity: 0.7,
            backgroundImageSaturation: 0.9,
            backgroundImageBlur: 32,
            backgroundImageHue: 335,
            backgroundImageContrast: 1,
            backgroundImageSize: 790,
            backgroundImagePositionX: 85,
            backgroundImagePositionY: 50,
            backgroundImageUrl: "https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&h=1500",

            newTabBackgroundImageOpacity: 0.65,
            newTabBackgroundImageSaturation: 0.65,
            newTabBackgroundImageBlur: 27,
            newTabBackgroundImageHue: 335,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImageSize: 390,
            newTabBackgroundImagePositionX: 100,
            newTabBackgroundImagePositionY: 100,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&h=1500",
        },
    },
    {
        name: "Purple Lights 1",
        configuration: {
            themeType: "dark",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageOpacity: 0.7,
            backgroundImageSaturation: 0.9,
            backgroundImageBlur: 32,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageSize: 790,
            backgroundImagePositionX: 85,
            backgroundImagePositionY: 50,
            backgroundImageUrl: "https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&h=1500",

            newTabBackgroundImageOpacity: 0.65,
            newTabBackgroundImageSaturation: 0.65,
            newTabBackgroundImageBlur: 27,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImageSize: 390,
            newTabBackgroundImagePositionX: 100,
            newTabBackgroundImagePositionY: 100,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&h=1500",
        },
    },
    {
        name: "Purple Lights 2",
        configuration: {
            themeType: "dark",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageBlur: 5,
            backgroundImageOpacity: 0.35,
            backgroundImageSaturation: 0.7,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/3109850/pexels-photo-3109850.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/3109850/pexels-photo-3109850.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Violet Wave",
        configuration: {
            themeType: "dark",
            theme: "violet",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageBlur: 5,
            backgroundImageOpacity: 0.6,
            backgroundImageSaturation: 1,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/4175070/pexels-photo-4175070.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/4175070/pexels-photo-4175070.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Gamer",
        configuration: {
            themeType: "dark",
            theme: "rose",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageOpacity: 0.35,
            backgroundImageSaturation: 0.7,
            backgroundImageBlur: 15,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageSize: 1200,
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageUrl: "https://images.pexels.com/photos/1212408/pexels-photo-1212408.jpeg?auto=compress&cs=tinysrgb&h=1500",

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/1212408/pexels-photo-1212408.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Silver Cubes",
        configuration: {
            themeType: "dark",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageOpacity: 0.4,
            backgroundImageSaturation: 0,
            backgroundImageBlur: 3,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/2346594/pexels-photo-2346594.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/2346594/pexels-photo-2346594.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0,
            newTabBackgroundImageBlur: 25,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Silver Circles",
        configuration: {
            themeType: "dark",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageBlur: 1,
            backgroundImageOpacity: 0.3,
            backgroundImageSaturation: 0,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/735812/pexels-photo-735812.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/735812/pexels-photo-735812.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Nice Pink",
        configuration: {
            themeType: "dark",
            theme: "violet",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageBlur: 3,
            backgroundImageOpacity: 0.5,
            backgroundImageSaturation: 0.8,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/3695378/pexels-photo-3695378.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/3695378/pexels-photo-3695378.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Girly",
        configuration: {
            themeType: "dark",
            theme: "rose",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageOpacity: 0.45,
            backgroundImageBlur: 5,
            backgroundImageSaturation: 0.75,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/3847178/pexels-photo-3847178.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/3847178/pexels-photo-3847178.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.25,
            newTabBackgroundImageSaturation: 0.8,
            newTabBackgroundImageBlur: 30,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
    {
        name: "Calm Gray",
        configuration: {
            themeType: "light",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,

            backgroundImageOpacity: 1,
            backgroundImageSaturation: 0.45,
            backgroundImageBlur: 3,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageSize: 275,
            backgroundImagePositionX: 50,
            backgroundImagePositionY: 50,
            backgroundImageUrl: "https://images.pexels.com/photos/1939485/pexels-photo-1939485.jpeg?auto=compress&cs=tinysrgb&h=1500",

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageOpacity: 0.7,
            newTabBackgroundImageSaturation: 0.45,
            newTabBackgroundImageBlur: 5,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImageSize: 105,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/1939485/pexels-photo-1939485.jpeg?auto=compress&cs=tinysrgb&h=1500",
        },
    },
    {
        name: "Blue Lines",
        configuration: {
            themeType: "light",
            theme: "blue",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageOpacity: 0.8,
            backgroundImageSaturation: 1,
            backgroundImageBlur: 4,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageSize: 1070,
            backgroundImagePositionX: 50,
            backgroundImagePositionY: 50,
            backgroundImageUrl: "https://images.pexels.com/photos/1029624/pexels-photo-1029624.jpeg?auto=compress&cs=tinysrgb&h=1500",

            newTabBackgroundImageOpacity: 0.8,
            newTabBackgroundImageSaturation: 1,
            newTabBackgroundImageBlur: 6,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImageSize: 800,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/1029624/pexels-photo-1029624.jpeg?auto=compress&cs=tinysrgb&h=1500",
        },
    },
    {
        name: "Beige",
        configuration: {
            themeType: "light",
            theme: "gray",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageBlur: 6,
            backgroundImageOpacity: 0.8,
            backgroundImageSaturation: 1,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImageUrl: "https://images.pexels.com/photos/1242348/pexels-photo-1242348.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 1200,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageBlur: 6,
            newTabBackgroundImageOpacity: 0.8,
            newTabBackgroundImageSaturation: 1,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/1242348/pexels-photo-1242348.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 1200,
        },
    },
    {
        name: "Light Violet",
        configuration: {
            themeType: "dark",
            theme: "violet",
            groupBgOpacity: 40,

            backgroundEnabled: false,
            backgroundColor: "linear-gradient(110deg, rgba(8, 25, 43, 1) 45%, rgb(25, 55, 85) 100%)",

            backgroundImageEnabled: true,
            backgroundImageUrl: "https://images.pexels.com/photos/2693200/pexels-photo-2693200.jpeg?auto=compress&cs=tinysrgb&h=1500",
            backgroundImageOpacity: 0.5,
            backgroundImageSaturation: 0.65,
            backgroundImageBlur: 8,
            backgroundImageHue: 0,
            backgroundImageContrast: 1,
            backgroundImagePositionX: 60,
            backgroundImagePositionY: 51,
            backgroundImageSize: 800,

            newTabBackgroundImageEnabled: true,
            newTabBackgroundImageUrl: "https://images.pexels.com/photos/2693200/pexels-photo-2693200.jpeg?auto=compress&cs=tinysrgb&h=1500",
            newTabBackgroundImageOpacity: 0.65,
            newTabBackgroundImageSaturation: 0.65,
            newTabBackgroundImageBlur: 12,
            newTabBackgroundImageHue: 0,
            newTabBackgroundImageContrast: 1,
            newTabBackgroundImagePositionX: 60,
            newTabBackgroundImagePositionY: 51,
            newTabBackgroundImageSize: 800,
        },
    },
];
